import Navbar from "@/components/common/navbar"
import './globals.css'
export const metadata = {
  title: 'Indranil-Portfolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#fffbf5] ">
        <div className={'app-container'}>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
